# Generated by Django 3.1.5 on 2021-01-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField(verbose_name='English')),
                ('spanish', models.TextField(verbose_name='Spanish')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translates.label')),
            ],
        ),
    ]
