# Generated by Django 3.1.5 on 2021-01-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['label__text']},
        ),
    ]
